### PR TITLE
issue91: Support Version 2.0.0 changes for document-approval-status

### PR DESCRIPTION
**Pull request by sunil-kumar-meena**
Fixed below issues:

- https://github.com/openBackhaul/TypeApprovalRegister/issues/91
- https://github.com/openBackhaul/TypeApprovalRegister/issues/90

Reviewer is @vanithavalluripalli9

### CODE REVIEW

**Review by vanithavalluripalli9 — CHANGES_REQUESTED** [review]
Kindly , move the functionality that includes read and write of application-data.json file and fetching applications list from application-data.json file to common file under ./individualServices

**Comment by sunil-kumar-meena** [comment]
> Kindly , move the functionality that includes read and write of application-data.json file and fetching applications list from application-data.json file to common file under ./individualServices

--this is done

**Review by vanithavalluripalli9 — DISMISSED** [review]
Approved.

**Review by vanithavalluripalli9 — CHANGES_REQUESTED** [review]
Kindly , remove the changes related to startApplicationInGenericRepresentation service which are not required.

**Comment by sunil-kumar-meena** [comment]
> Kindly , remove the changes related to startApplicationInGenericRepresentation service which are not required.

done

**Review by vanithavalluripalli9 — APPROVED** [review]

**Pull request merged**
