### PR TITLE
issue160: Implement OAM Services for version 2.0.0

### PR DESCRIPTION
**Pull request by sunil-kumar-meena**
Fixed below issues
https://github.com/openBackhaul/TypeApprovalRegister/issues/160
https://github.com/openBackhaul/TypeApprovalRegister/issues/109

Note: Reviewer is @vanithavalluripalli9

### CODE REVIEW

**Review by vanithavalluripalli9 — CHANGES_REQUESTED** [review]
All the put requests of layerprotocol services httpClient,TcpServer,TcpClient,Operationserver,Operationclient should include forwarding to ALT if information is updated

**Comment by sunil-kumar-meena** [comment]
> All the put requests of layerprotocol services httpClient,TcpServer,TcpClient,Operationserver,Operationclient should include forwarding to ALT if information is updated

-- This is done

**Comment by sunil-kumar-meena** [comment]
> Kindly , add forwardings to ALT for put services of operation- client and operation-server

done

**Comment by sunil-kumar-meena** [comment]
> All the put requests of layerprotocol services httpClient,TcpServer,TcpClient,Operationserver,Operationclient should include forwarding to ALT if information is updated

done

**Review by vanithavalluripalli9 — APPROVED** [review]

**Pull request merged**
